---
- name: debug
  debug:
    msg: "jeste namede"

- block:
    - name: install named
      yum:
        name:
          - bind
          - bind-utils
        state: installed

    - name: create zones directory
      file:
        path: /var/named/zones
        state: directory
        owner: named
        mode: 0755

    - name: create dnssec key
      command: dnssec-keygen -a HMAC-MD5 -b 512 -n HOST ansible
      args:
        chdir: /var/named
        creates: "Kansible*"
      register: _dnsseckey

    - name: symlink keys
      file:
        src: "/var/named/{{ _dnsseckey.stdout }}.{{ item }}"
        dest: "/var/named/Kansible.{{ item }}"
        state: link
      loop:
        - key
        - private
      when: _dnsseckey.changed

    - name: read the dnsseckey
      shell: "grep Key: /var/named/Kansible.private|awk '{print $2}'"
      register: _dnsseckey_value
      check_mode: false
      changed_when: false

    - name: copy named.conf
      template:
        src: named.conf
        dest: /etc/named.conf
        mode: 0640
        owner: named
      notify: restart named

    - name: copy zone file
      template:
        src: zone.conf
        dest: "/var/named/zones/{{ zone.key }}.zone"
        mode: 0640
        owner: named
      loop: "{{ app.value.named.configs.zones|dict2items }}"
      when: zone.value.type != "forward"
      loop_control:
        loop_var: zone
      notify: restart named


    - name: deb
      vars:
        ports: "{{ app.value.named.configs.listen[item[0]].ports|default([])|list|join(',') }}"
      debug:
        msg: "{{ ports }}"
      loop: "{{ ['ipv4','ipv6']|product(['tcp','udp'])|list }}"

    - name: allow ports on selinux
      vars:
        ports: "{{ app.value.named.configs.listen[item[0]].ports|default([])|list|join(',') }}"
      seport:
        ports: "{{ ports }}"
        proto: "{{ item[1] }}"
        setype: dns_port_t
        state: present
      loop: "{{ ['ipv4','ipv6']|product(['tcp','udp'])|list }}"
      when: ports|length

    - name: run handlers
      meta: flush_handlers

    - name: start and enable named
      service:
        name: named
        state: started
        enabled: true
  become: true
  become_user: root
